layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: andrew-guest-a891759a
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 11343576
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: https://andrewguest.github.io/
  # youtube: your_username

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: FastAPI
    web_url: https://github.com/topics/fastapi
    image_url: https://fastapi.tiangolo.com/img/logo-margin/logo-teal.png

  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png

  - name: MongoDB
    web_url: https://github.com/topics/mongodb
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/mongodb/mongodb.png

  - name: GraphQL
    web_url: https://github.com/topics/graphql
    image_url: https://raw.githubusercontent.com/github/explore/5c058a388828bb5fde0bcafd4bc867b5bb3f26f3/topics/graphql/graphql.png

  - name: API
    web_url: https://github.com/topics/api

subdomains:
  - name: Anime API
    description: API created with FastAPI and Beanie to connect to a MongoDB database for storing anime shows and movies.
    subdomain_url: https://anime-api.aguest.me/docs#/
    technologies:
      - FastAPI
      - MongoDB
      - Beanie
      - Caddy web server
