layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: andrew-guest-a891759a
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 11343576
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: https://andrewguest.github.io/
  # youtube: your_username

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Svelte
    web_url: https://github.com/topics/svelte
    image_url: https://raw.githubusercontent.com/github/explore/42198dc9113595ddd22cc12771bb719c8cf08b67/topics/svelte/svelte.png

  - name: Flutter
    web_url: https://github.com/topics/flutter
    image_url: https://raw.githubusercontent.com/github/explore/cebd63002168a05a6a642f309227eefeccd92950/topics/flutter/flutter.png

  - name: PostgreSQL
    web_url: https://github.com/topics/postgres
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/postgresql/postgresql.png

  - name: MongoDB
    web_url: https://github.com/topics/mongodb
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/mongodb/mongodb.png

subdomains:
  - name: Quotes API
    description: API created with FastAPI that returns random quotes. This API runs on a Kubernetes cluster.
    subdomain_url: https://ruling-monkey-certainly.ngrok-free.app/quotes-api/quotes
    technologies:
      - FastAPI
      - Kubernetes

  # - name: WebSocket API
  #   description: API created with FastAPI to show how to work with WebSockets
  #   subdomain_url: https://websocket.aguest.me/
  #   technologies:
  #     - FastAPI
  #     - WebSockets

  # - name: MovieShelf
  #   description: Web app for showing my movie and TV show collection.
  #   subdomain_url: https://movie-shelf.aguest.me/
  #   technologies:
  #     - SvelteKit
  #     - Tailwind CSS

  # - name: MovieShelf API
  #   description: API to support the MovieShelf frontend
  #   subdomain_url: https://movie-shelf-api.aguest.me/movies
  #   technologies:
  #     - FastAPI
  #     - PostgreSQL
